### ISSUE TITLE
Won't Work at all

### ISSUE THREAD

**Issue by pardisproud** [Mashrien/MashTools#8]
I can't get it to work at all whatsoever, but if your  wondering i just want people to get items on (respawn) and not able to use the command. like you said. I'm sure it's something I'm doing. I am using the newest server and rocket, and all other plugins work fine.

![untitled](https://cloud.githubusercontent.com/assets/13142146/8466508/3b66634e-2019-11e5-8829-14d1d22ab9ee.png)

Please help,  pardisproud

**Comment by Mashrien** [comment]
DeathAnnounce doesn't require a permission and gearup only needs the highest permission you want them to have.. in your case: Remove gearup.info and leave only gearup.self (since gearup.self contains all of .info's permissions)

**Comment by pardisproud** [comment]
If I don't have a permission for DeathAnnounce it worn't show up but I'm assuming you changed that. And i just put gearup.info in there because it said each perm also gives the perms above it. I know it doesn't give them anything if they have items in their inventory because thats why i like it. It seems you've added another updated plugin so I'll try tha

**Comment by Mashrien** [comment]
If you're still having issues, please let me know. Otherwise I'll be closing this issue as resolved. :)

**Comment by pardisproud** [comment]
"installed" the newest plugin and it works fine now, thanks a lot for the help!

24.220.140.138
27015
